spring:
  application:
    name: fan-ai-agent
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:}
      chat:
        base-url: ${DASHSCOPE_BASE_URL:https://dashscope.aliyuncs.com}
        options:
          model: ${DASHSCOPE_CHAT_MODEL:qwen-plus}
          multi-model: ${DASHSCOPE_MULTI_MODEL:false}
      embedding:
        options:
          model: ${DASHSCOPE_EMBEDDING_MODEL:text-embedding-v3}
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        model: ${OLLAMA_CHAT_MODEL:gemma3:1b}
    mcp:
      client:
        sse:
          connections:
            image-search:
              url: ${IMAGE_MCP_URL:http://localhost:8127}
        stdio:
          servers-configuration: classpath:mcp-servers.json
# 临时注释掉，便于大家开发调试和部署（实际需要启动 PgVector 数据库）
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        dimensions: 1536
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
server:
  port: ${SERVER_PORT:8123}
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.fan.fanaiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchAPI
search-api:
  api-key: ${SEARCH_API_KEY:}
logging:
  level:
    org.springframework.ai: ${SPRING_AI_LOG_LEVEL:INFO}
